### ISSUE TITLE
Is this english rule right?

### ISSUE THREAD

**Issue by thevinci** [tj/lingo#10]
I see this in the english file

```
en.singular(/ies$/i, 'ie')
```

Should this be?

```
en.singular(/ies$/i, 'y')  
```

**Comment by tremby** [comment]
Sometimes yes, sometimes no.

Some from the no camp:
- oldie
- pie
- pinkie
- pixie
- prairie
- quickie
- rookie
- rotisserie
- sweetie
- veggie
- zombie

Some from the yes camp:
- ability
- abnormality
- academy
- city
- melody
- ovary
- reply
- try
