### ISSUE TITLE
No Progress

### ISSUE THREAD

**Issue by WickedSik** [tj/lingo#29]
As nothing seems to happen on this repo, I'm going to try and keep it active, that is, I'm making a true clone of this project, and hope that people are willing to continue this module with me.

It can be found here : https://github.com/WickedCoding/lingo

**Comment by tj** [comment]
what's your npm username? I can add you, we just haven't had anyone interested in maintaining

**Comment by WickedSik** [comment]
my npm username is jpdokter

**Comment by tj** [comment]
added!
