### ISSUE TITLE
Fails to singularize 'activities' to 'activity'. Returns 'activitie'.

### ISSUE THREAD

**Issue by allanca** [tj/lingo#7]
There's a direct conflict between 'activities' and 'movies'. 

There are two rules that handle the ies -> y and ies -> ie cases. In the current order, they get movies right but fail on activities. When switched, they get activities right but fail on movies.

Could make 'activities' irregular, but there are a bunch of other words that follow that pattern, e.g., berries.

Could make 'movies' irregular, but there are a bunch of other words that follow that pattern, e.g., mostly slang words like talkies, cuties, movies, etc.

There's a definite split in the rule with no clear regex that could divine the correct singularization.

**Comment by dbrain** [comment]
This should be fixed since the merge this morning.
https://github.com/visionmedia/lingo/commit/20b61aad5693593d31501cd8a7a433cebfda9952

**Comment by allanca** [comment]
That fix did it. Thanks.
